baseURL = "https://phamvunhatminh.github.io/AWS-FCJ-Workshop/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
  # Color scheme variant
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "thienlh@thienlu.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[languages]
  [languages.en]
    title = "Internship Report"
    weight = 1
    languageName = "English"
    contentDir = "content/en"

    [[languages.en.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group"
      identifier = "AWS Study Group FB"
      url = "https://www.facebook.com/groups/awsstudygroupfcj/"
      weight = 20

  [languages.vi]
    title = "Báo cáo thực tập"
    weight = 2
    languageName = "Tiếng Việt"
    contentDir = "content/vi"

    [[languages.vi.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group"
      identifier = "AWS Study Group FB"
      url = "https://www.facebook.com/groups/awsstudygroupfcj/"
      weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
